using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace Pihalve.PlaylistConverter.Application.Domain
{
    public class Country : ICloneable
    {
        public Country(string twoLetterIsoLanguageName, string name)
        {
            TwoLetterIsoLanguageName = twoLetterIsoLanguageName;
            Name = name;
        }

        public string TwoLetterIsoLanguageName { get; set; }
        public string Name { get; set; }

        public static Country GetCurrentCultureCountry()
        {
            string countryCode = CultureInfo.CurrentCulture.IsNeutralCulture ? "US" : CultureInfo.CurrentCulture.Name.Split('-')[1];
            return Countries.SingleOrDefault(x => x.TwoLetterIsoLanguageName == countryCode);
        }

        public override string ToString()
        {
            return string.Format("{0} ({1})", TwoLetterIsoLanguageName, Name);
        }

        public object Clone()
        {
            return new Country(TwoLetterIsoLanguageName, Name);
        }

        public static readonly IEnumerable<Country> Countries = new HashSet<Country>
        {
            new Country("AD", "Andorra"),
            new Country("AE", "United Arab Emirates"),
            new Country("AF", "Afghanistan"),
            new Country("AG", "Antigua and Barbuda"),
            new Country("AI", "Anguilla"),
            new Country("AL", "Albania"),
            new Country("AM", "Armenia"),
            new Country("AO", "Angola"),
            new Country("AQ", "Antarctica"),
            new Country("AR", "Argentina"),
            new Country("AS", "American Samoa"),
            new Country("AT", "Austria"),
            new Country("AU", "Australia"),
            new Country("AW", "Aruba"),
            new Country("AX", "Åland Islands"),
            new Country("AZ", "Azerbaijan"),
            new Country("BA", "Bosnia and Herzegovina"),
            new Country("BB", "Barbados"),
            new Country("BD", "Bangladesh"),
            new Country("BE", "Belgium"),
            new Country("BF", "Burkina Faso"),
            new Country("BG", "Bulgaria"),
            new Country("BH", "Bahrain"),
            new Country("BI", "Burundi"),
            new Country("BJ", "Benin"),
            new Country("BL", "Saint Barthélemy"),
            new Country("BM", "Bermuda"),
            new Country("BN", "Brunei Darussalam"),
            new Country("BO", "Bolivia"),
            new Country("BQ", "Bonaire"),
            new Country("BR", "Brazil"),
            new Country("BS", "Bahamas"),
            new Country("BT", "Bhutan"),
            new Country("BV", "Bouvet Island"),
            new Country("BW", "Botswana"),
            new Country("BY", "Belarus"),
            new Country("BZ", "Belize"),
            new Country("CA", "Canada"),
            new Country("CC", "Cocos (Keeling) Islands"),
            new Country("CD", "Congo"),
            new Country("CF", "Central African Republic"),
            new Country("CG", "Congo"),
            new Country("CH", "Switzerland"),
            new Country("CI", "Côte d'Ivoire"),
            new Country("CK", "Cook Islands"),
            new Country("CL", "Chile"),
            new Country("CM", "Cameroon"),
            new Country("CN", "China"),
            new Country("CO", "Colombia"),
            new Country("CR", "Costa Rica"),
            new Country("CU", "Cuba"),
            new Country("CV", "Cape Verde"),
            new Country("CW", "Curaçao"),
            new Country("CX", "Christmas Island"),
            new Country("CY", "Cyprus"),
            new Country("CZ", "Czech Republic"),
            new Country("DE", "Germany"),
            new Country("DJ", "Djibouti"),
            new Country("DK", "Denmark"),
            new Country("DM", "Dominica"),
            new Country("DO", "Dominican Republic"),
            new Country("DZ", "Algeria"),
            new Country("EC", "Ecuador"),
            new Country("EE", "Estonia"),
            new Country("EG", "Egypt"),
            new Country("EH", "Western Sahara"),
            new Country("ER", "Eritrea"),
            new Country("ES", "Spain"),
            new Country("ET", "Ethiopia"),
            new Country("FI", "Finland"),
            new Country("FJ", "Fiji"),
            new Country("FK", "Falkland Islands (Malvinas)"),
            new Country("FM", "Micronesia"),
            new Country("FO", "Faroe Islands"),
            new Country("FR", "France"),
            new Country("GA", "Gabon"),
            new Country("GB", "United Kingdom"),
            new Country("GD", "Grenada"),
            new Country("GE", "Georgia"),
            new Country("GF", "French Guiana"),
            new Country("GG", "Guernsey"),
            new Country("GH", "Ghana"),
            new Country("GI", "Gibraltar"),
            new Country("GL", "Greenland"),
            new Country("GM", "Gambia"),
            new Country("GN", "Guinea"),
            new Country("GP", "Guadeloupe"),
            new Country("GQ", "Equatorial Guinea"),
            new Country("GR", "Greece"),
            new Country("GS", "South Georgia and the South Sandwich Islands"),
            new Country("GT", "Guatemala"),
            new Country("GU", "Guam"),
            new Country("GW", "Guinea-Bissau"),
            new Country("GY", "Guyana"),
            new Country("HK", "Hong Kong"),
            new Country("HM", "Heard Island and McDonald Islands"),
            new Country("HN", "Honduras"),
            new Country("HR", "Croatia"),
            new Country("HT", "Haiti"),
            new Country("HU", "Hungary"),
            new Country("ID", "Indonesia"),
            new Country("IE", "Ireland"),
            new Country("IL", "Israel"),
            new Country("IM", "Isle of Man"),
            new Country("IN", "India"),
            new Country("IO", "British Indian Ocean Territory"),
            new Country("IQ", "Iraq"),
            new Country("IR", "Iran"),
            new Country("IS", "Iceland"),
            new Country("IT", "Italy"),
            new Country("JE", "Jersey"),
            new Country("JM", "Jamaica"),
            new Country("JO", "Jordan"),
            new Country("JP", "Japan"),
            new Country("KE", "Kenya"),
            new Country("KG", "Kyrgyzstan"),
            new Country("KH", "Cambodia"),
            new Country("KI", "Kiribati"),
            new Country("KM", "Comoros"),
            new Country("KN", "Saint Kitts and Nevis"),
            new Country("KP", "Korea (Democratic People's Republic)"),
            new Country("KR", "Korea (Republic"),
            new Country("KW", "Kuwait"),
            new Country("KY", "Cayman Islands"),
            new Country("KZ", "Kazakhstan"),
            new Country("LA", "Lao People's Democratic Republic"),
            new Country("LB", "Lebanon"),
            new Country("LC", "Saint Lucia"),
            new Country("LI", "Liechtenstein"),
            new Country("LK", "Sri Lanka"),
            new Country("LR", "Liberia"),
            new Country("LS", "Lesotho"),
            new Country("LT", "Lithuania"),
            new Country("LU", "Luxembourg"),
            new Country("LV", "Latvia"),
            new Country("LY", "Libya"),
            new Country("MA", "Morocco"),
            new Country("MC", "Monaco"),
            new Country("MD", "Moldova"),
            new Country("ME", "Montenegro"),
            new Country("MF", "Saint Martin (French part)"),
            new Country("MG", "Madagascar"),
            new Country("MH", "Marshall Islands"),
            new Country("MK", "Macedonia"),
            new Country("ML", "Mali"),
            new Country("MM", "Myanmar"),
            new Country("MN", "Mongolia"),
            new Country("MO", "Macao"),
            new Country("MP", "Northern Mariana Islands"),
            new Country("MQ", "Martinique"),
            new Country("MR", "Mauritania"),
            new Country("MS", "Montserrat"),
            new Country("MT", "Malta"),
            new Country("MU", "Mauritius"),
            new Country("MV", "Maldives"),
            new Country("MW", "Malawi"),
            new Country("MX", "Mexico"),
            new Country("MY", "Malaysia"),
            new Country("MZ", "Mozambique"),
            new Country("NA", "Namibia"),
            new Country("NC", "New Caledonia"),
            new Country("NE", "Niger"),
            new Country("NF", "Norfolk Island"),
            new Country("NG", "Nigeria"),
            new Country("NI", "Nicaragua"),
            new Country("NL", "Netherlands"),
            new Country("NO", "Norway"),
            new Country("NP", "Nepal"),
            new Country("NR", "Nauru"),
            new Country("NU", "Niue"),
            new Country("NZ", "New Zealand"),
            new Country("OM", "Oman"),
            new Country("PA", "Panama"),
            new Country("PE", "Peru"),
            new Country("PF", "French Polynesia"),
            new Country("PG", "Papua New Guinea"),
            new Country("PH", "Philippines"),
            new Country("PK", "Pakistan"),
            new Country("PL", "Poland"),
            new Country("PM", "Saint Pierre and Miquelon"),
            new Country("PN", "Pitcairn"),
            new Country("PR", "Puerto Rico"),
            new Country("PS", "Palestine"),
            new Country("PT", "Portugal"),
            new Country("PW", "Palau"),
            new Country("PY", "Paraguay"),
            new Country("QA", "Qatar"),
            new Country("RE", "Réunion"),
            new Country("RO", "Romania"),
            new Country("RS", "Serbia"),
            new Country("RU", "Russian Federation"),
            new Country("RW", "Rwanda"),
            new Country("SA", "Saudi Arabia"),
            new Country("SB", "Solomon Islands"),
            new Country("SC", "Seychelles"),
            new Country("SD", "Sudan"),
            new Country("SE", "Sweden"),
            new Country("SG", "Singapore"),
            new Country("SH", "Saint Helena"),
            new Country("SI", "Slovenia"),
            new Country("SJ", "Svalbard and Jan Mayen"),
            new Country("SK", "Slovakia"),
            new Country("SL", "Sierra Leone"),
            new Country("SM", "San Marino"),
            new Country("SN", "Senegal"),
            new Country("SO", "Somalia"),
            new Country("SR", "Suriname"),
            new Country("SS", "South Sudan"),
            new Country("ST", "Sao Tome and Principe"),
            new Country("SV", "El Salvador"),
            new Country("SX", "Sint Maarten (Dutch part)"),
            new Country("SY", "Syrian Arab Republic"),
            new Country("SZ", "Swaziland"),
            new Country("TC", "Turks and Caicos Islands"),
            new Country("TD", "Chad"),
            new Country("TF", "French Southern Territories"),
            new Country("TG", "Togo"),
            new Country("TH", "Thailand"),
            new Country("TJ", "Tajikistan"),
            new Country("TK", "Tokelau"),
            new Country("TL", "Timor-Leste"),
            new Country("TM", "Turkmenistan"),
            new Country("TN", "Tunisia"),
            new Country("TO", "Tonga"),
            new Country("TR", "Turkey"),
            new Country("TT", "Trinidad and Tobago"),
            new Country("TV", "Tuvalu"),
            new Country("TW", "Taiwan"),
            new Country("TZ", "Tanzania"),
            new Country("UA", "Ukraine"),
            new Country("UG", "Uganda"),
            new Country("UM", "United States Minor Outlying Islands"),
            new Country("US", "United States"),
            new Country("UY", "Uruguay"),
            new Country("UZ", "Uzbekistan"),
            new Country("VA", "Holy See (Vatican City State)"),
            new Country("VC", "Saint Vincent and the Grenadines"),
            new Country("VE", "Venezuela"),
            new Country("VG", "Virgin Islands (British)"),
            new Country("VI", "Virgin Islands (U.S.)"),
            new Country("VN", "Viet Nam"),
            new Country("VU", "Vanuatu"),
            new Country("WF", "Wallis and Futuna"),
            new Country("WS", "Samoa"),
            new Country("YE", "Yemen"),
            new Country("YT", "Mayotte"),
            new Country("ZA", "South Africa"),
            new Country("ZM", "Zambia"),
            new Country("ZW", "Zimbabwe")
        };
    }
}
